name: SFS-readthedocs
dependencies:
  - python==3.5
  - sphinx>=1.3
  - sphinx_rtd_theme
  - numpy
  - scipy<=0.18
  - matplotlib>=1.5
  - pip:
    - sfs
    - git+https://github.com/hagenw/sphinxcontrib-katex@3.0
